name: Create release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Zip Folder
      run: zip -r ${{ github.event.repository.name }}.zip . --include "./VSFSM" 

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.event.repository.name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}